### ISSUE TITLE
Alternative clojure client libraries

### ISSUE THREAD

**Issue by prateekbhatt** [iron-io/iron_mq_clojure#10]
Since this is deprecated now, what are the alternative clojure client libraries for using ironmq ? The other options are using the java client via clojure or using the REST API, but are you aware of any maintained clojure client libs ?

**Comment by rdallman** [comment]
Hi @prateekbhatt https://github.com/efficiosro/clj-ironmq will work with ironmq v3 but it's not an officially supported client under our umbrella at present.

**Comment by prateekbhatt** [comment]
Thanks @rdallman that should work, any plans for an officially supported client soon ?

**Comment by rdallman** [comment]
we could fork it at some point, but there's nothing planned.

**Comment by prateekbhatt** [comment]
ok, cool
